apiVersion: v1
kind: Service
metadata:
  name: express-frontend
spec:
  type: NodePort
  selector:
    app: express-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-frontend
  template:
    metadata:
      labels:
        app: express-frontend
    spec:
      containers:
        - name: express
          image: express-frontend:local
          ports:
            - containerPort: 3000
